// ✏️ Edit this file to update the portfolio content.
window.PORTFOLIO = {
  name: "S Harshni",
  short: "harshni",
  role: "Full-Stack Software Development Engineer",
  status: "Open to SDE roles · 2027 graduate",
  roles: ["Full-Stack Software Engineer", "Backend & API Developer", "Cloud & AI Builder"],
  tagline:
    "I build scalable server-side systems, fast REST APIs and clean React/Next.js frontends — with a focus on performance, reliability and ownership.",
  links: {
    github: "https://github.com/S-Harshni",
    linkedin: "https://www.linkedin.com/in/ks-harshni/",
    email: "ksharshni05@gmail.com",
  },
  terminal: {
    name: "S Harshni",
    role: "SDE · Full-Stack",
    stack: "Node · Next.js · Python · SQL",
    cloud: "AWS · Docker · Kubernetes",
    based: "Chennai, India",
  },
  stats: [
    { value: "500+", label: "daily users served" },
    { value: "99.9%", label: "API uptime" },
    { value: "<200ms", label: "response on hot endpoints" },
    { value: "10+", label: "industry certifications" },
  ],
  about: [
    "I'm a <strong>Full-stack Software Development Engineer</strong> pursuing a B.Tech in Computer Science (AI &amp; ML) at SRM Institute of Science and Technology, graduating in 2027.",
    "As an SDE intern at <strong>InAmigos Foundation</strong>, I designed server-side architecture and RESTful APIs serving 500+ daily active users at 99.9% uptime, and owned an AI-powered inventory system end to end.",
    "I work across <strong>Node.js, TypeScript, React, Next.js, Tailwind CSS and SQL</strong>, with hands-on AWS, Docker and Git. I take ownership, learn fast and enjoy fast-paced, startup-style teams.",
  ],
  facts: [
    { icon: "pin", label: "Location", value: "Chennai, India" },
    { icon: "cap", label: "Education", value: "B.Tech CSE (AI & ML) · CGPA 8.65" },
    { icon: "brief", label: "Latest role", value: "SDE Intern · InAmigos Foundation" },
    { icon: "star", label: "Focus", value: "APIs · Databases · Web performance" },
  ],
  experience: [
    {
      title: "Software Development Engineer Intern",
      company: "InAmigos Foundation",
      date: "Jan 2026 – May 2026",
      place: "Chennai",
      points: [
        "Designed and built scalable server-side architecture and RESTful APIs (Python, Flask) supporting 500+ daily active users at 99.9% uptime.",
        "Resolved performance bottlenecks by optimizing SQL queries, data pipelines and load distribution, achieving sub-200ms response times on high-traffic endpoints.",
        "Owned an AI-powered inventory system end to end, from requirements to deployment, improving query accuracy by 40%.",
        "Automated manual inventory workflows, saving 10+ hours of manual effort per week.",
      ],
      tags: ["Python", "Flask", "REST APIs", "SQL", "AI"],
    },
  ],
  projects: [
    {
      title: "Retail Intelligence Platform",
      subtitle: "Forecasting, customer model and recommendations",
      category: "Data",
      glyph: "£",
      colors: ["#2a78d6", "#1baf7a"],
      metric: { value: "1.07M", label: "real retail transactions" },
      points: [
        "Analytics and models on two years of a UK online retailer's orders, over a SQL warehouse.",
        "Repeat-purchase model: ROC AUC 0.80 on a later 90-day window; 92% of the top tenth ordered.",
        "Weekly demand forecast for 791 products: 10% lower error than the best simple rule over 3 weeks.",
        "Bought-together recommender: 29.8% hit rate in the top 10, 8.6× the best-seller baseline.",
      ],
      tags: ["Python", "SQL", "DuckDB", "scikit-learn", "FastAPI"],
      github: "https://github.com/S-Harshni/Retail-Intelligence-Platform",
      live: "https://s-harshni.github.io/Retail-Intelligence-Platform/",
    },
    {
      title: "Turbofan Predictive Maintenance",
      subtitle: "Remaining-life prediction and maintenance queue",
      category: "AI / ML",
      glyph: "⚙",
      colors: ["#0b5cad", "#0e7490"],
      metric: { value: "11.3", label: "cycles test RMSE · 35% lower than raw sensors" },
      points: [
        "Predicts remaining useful life of jet engines on NASA's C-MAPSS benchmark (33,700+ operating cycles).",
        "Leakage-free rolling and drift features; evaluated on 100 held-out engines.",
        "Alerts catch 22 of 25 engines within 30 cycles of failure, with no false alerts.",
        "Ranked maintenance queue with uncertainty ranges; 8 tests in CI and a live dashboard.",
      ],
      tags: ["Python", "scikit-learn", "pandas", "Time series", "Chart.js"],
      github: "https://github.com/S-Harshni/Turbofan-Predictive-Maintenance",
      live: "https://s-harshni.github.io/Turbofan-Predictive-Maintenance/",
    },
    {
      title: "Radar Signal Processing Simulator",
      subtitle: "Pulse-Doppler radar chain in C++, MATLAB & JS",
      category: "DSP",
      glyph: "∿",
      colors: ["#0e7490", "#1d4ed8"],
      metric: { value: "15 m", label: "range resolution · 41 dB gain" },
      points: [
        "LFM chirp waveform, FFT-based matched filter (pulse compression) and Doppler FFT.",
        "Swerling 0–IV targets, radar range equation, 2-D CA-CFAR detection.",
        "Radix-2 FFT from scratch; 20 unit tests against theory, run in CI.",
        "Interactive in-browser demo plus a MATLAB reference script.",
      ],
      tags: ["C++17", "MATLAB", "FFT", "CFAR", "Radar"],
      github: "https://github.com/S-Harshni/Radar-Signal-Processing-Simulator",
      live: "https://s-harshni.github.io/Radar-Signal-Processing-Simulator/",
    },
    {
      title: "MERN Amazona",
      subtitle: "Full-stack e-commerce platform",
      category: "Full-Stack",
      glyph: "{ }",
      colors: ["#2f6fed", "#7c3aed"],
      metric: { value: "20%", label: "faster page loads via lazy loading" },
      points: [
        "Amazon-style store with product search, cart, checkout, orders and user profiles.",
        "Backend on Next.js API routes (no Express); 10+ REST endpoints tested with Postman.",
        "JWT auth with Prisma ORM on PostgreSQL/MySQL, cutting query latency by 15%.",
        "Admin dashboard for products, orders and users.",
      ],
      tags: ["Next.js", "React", "Node.js", "Tailwind", "Prisma", "SQL"],
      github: "https://github.com/S-Harshni/Amazon-Clone-MernStack",
      live: "https://s-harshni.github.io/Amazon-Clone-MernStack/",
    },
    {
      title: "Smart Meeting Assistant Agent",
      subtitle: "AI agent for meeting notes → tasks",
      category: "AI / ML",
      glyph: "AI",
      colors: ["#0fb5a6", "#2563eb"],
      metric: { value: "40%", label: "less follow-up time" },
      points: [
        "Agno + LLMs (Nebius API) turn raw notes into summaries of decisions and next steps.",
        "Linear API integration auto-creates tasks from meeting discussions.",
        "Slack bot posts summaries and alerts to the team channel in real time.",
        "Streamlit UI with chat input and secure API-key entry; deps managed with uv.",
      ],
      tags: ["Python", "Agno", "LLMs", "Linear API", "Slack API", "Streamlit"],
      github: "https://github.com/S-Harshni/Smart-Meeting-Assistant-Agent",
    },
    {
      title: "AI Fashion Recommender",
      subtitle: "Deep-learning visual recommendations",
      category: "AI / ML",
      glyph: "◎",
      colors: ["#db2777", "#f59e0b"],
      metric: { value: "289K+", label: "images · 85%+ accuracy" },
      points: [
        "ResNet classifier in TensorFlow trained on DeepFashion (50 categories).",
        "Modular pipeline: preprocessing, augmentation, configurable hyperparameters, train/test scripts.",
        "Nearest-neighbor recommender with sub-100ms inference and sub-second retrieval.",
      ],
      tags: ["Python", "TensorFlow", "ResNet", "k-NN"],
      github: "https://github.com/S-Harshni/AI-Powered-Fashion-Recommendation-System",
      live: "https://s-harshni.github.io/AI-Powered-Fashion-Recommendation-System/",
    },
    {
      title: "Myntra Returns-Reduction Analysis",
      subtitle: "Business analytics dashboard",
      category: "Data",
      glyph: "▦",
      colors: ["#ea580c", "#be123c"],
      metric: { value: "15%", label: "projected drop in return rate" },
      points: [
        "Analyzed 10K+ Myntra sales records in Power BI and Excel.",
        "Defined business requirements and KPIs for revenue, orders and products.",
        "Interactive dashboard: top brands, daily sales by category, sales across 20+ states.",
      ],
      tags: ["Power BI", "Excel", "KPIs"],
      github: "https://github.com/S-Harshni/myntra-returns-reduction-analysis",
      live: "https://s-harshni.github.io/myntra-returns-reduction-analysis/",
    },
  ],
  skills: {
    Languages: ["JavaScript", "TypeScript", "Python", "Java", "SQL", "C++", "HTML/CSS"],
    Frontend: ["React.js", "Next.js", "Tailwind CSS", "Streamlit"],
    Backend: ["Node.js", "Next.js API Routes", "Flask", "Spring Boot", "REST API Design", "JWT Auth", "Prisma ORM"],
    Databases: ["MySQL", "PostgreSQL", "MongoDB", "Query Optimization"],
    "Cloud & DevOps": ["AWS (Lambda, ECS, EKS, CloudWatch)", "GCP", "Docker", "Kubernetes", "Jenkins", "Kafka", "RabbitMQ"],
    Tools: ["Git", "GitHub", "GitLab", "Postman", "Grafana", "Splunk"],
  },
  education: [
    {
      school: "SRM Institute of Science and Technology",
      date: "Aug 2023 – May 2027",
      degree: "B.Tech, Computer Science & Engineering (AI & ML) · Kattankulathur, Chennai",
      score: "CGPA 8.65 / 10",
      coursework:
        "DSA · Design & Analysis of Algorithms · DBMS · OOP · Operating Systems · Computer Networks · Software Engineering",
    },
  ],
  certs: [
    "AWS Certified Developer – Associate",
    "AWS Certified Cloud Practitioner (2025)",
    "Oracle Certified Professional: MySQL 8.0 Database Developer",
    "MongoDB Associate Developer (Node.js)",
    "Meta Back-End Developer Professional Certificate",
    "OCI Generative AI Professional (2026)",
    "Microsoft Azure Fundamentals AZ-900 · Azure AI Fundamentals AI-900",
    "Microsoft Power BI Data Analyst PL-300 · Excel",
    "Google Data Analytics",
  ],
  contactText:
    "I'm looking for Software Development Engineer roles and internships. Whether you have an opportunity or just want to connect, my inbox is open.",
};
